// THIS FILE WAS GENERATED BY DEEPWELL v0.0.1

type Nullable<T> = T | null;

export interface AuthorsModel {
  page_id: number;
  user_id: number;
  author_type: string;
  created_at: Date;
}

export interface FilesModel {
  file_id: number;
  file_name: string;
  file_uri: string;
  description: string;
  page_id: number;
}

export interface PagesModel {
  page_id: number;
  created_at?: Date;
  slug: string;
  title: string;
  alt_title: Nullable<string>;
  tags: string[];
}

export interface ParentsModel {
  page_id: number;
  parent_page_id: number;
}

export interface RevisionsModel {
  revision_id: number;
  created_at?: Date;
  page_id: number;
  user_id: number;
  git_commit: string;
  changes: object;
}

export interface UsersModel {
  user_id: number;
  name: string;
  created_at?: Date;
}

export interface RatingsModel {
  page_id: number;
  user_id: number;
  rating: number;
}

export interface RatingsHistoryModel {
  rating_id: number;
  page_id: number;
  user_id: number;
  created_at?: Date;
  rating: Nullable<number>;
}

