// THIS FILE WAS AUTOGENERATED BY DEEPWELL v0.0.1
// DO NOT EDIT - MODIFY TEMPLATE INSTEAD

type Nullable<T> = T | null;


export interface AuthorModel {
    // Has default value
    page_id: number;

    // Has default value
    user_id: number;

    author_type: string;

    created_at: Date;

}

export interface FileModel {
    // Has default value
    file_id: number;

    file_name: string;

    file_uri: string;

    description: string;

    // Has default value
    page_id: number;

}

export interface PageModel {
    // Has default value
    page_id: number;

    // Has default value
    created_at: Date;

    slug: string;

    title: string;

    alt_title: Nullable<string>;

    tags: string[];

}

export interface ParentModel {
    // Has default value
    page_id: number;

    // Has default value
    parent_page_id: number;

    // Has default value
    parented_by: number;

    parented_at: Date;

}

export interface PasswordModel {
    // Has default value
    user_id: number;

    hash: Buffer;

    salt: Buffer;

    iterations: number;

    key_size: number;

    digest: string;

}

export interface RatingModel {
    // Has default value
    page_id: number;

    // Has default value
    user_id: number;

    rating: number;

}

export interface RatingsHistoryModel {
    // Has default value
    rating_id: number;

    // Has default value
    page_id: number;

    // Has default value
    user_id: number;

    // Has default value
    created_at: Date;

    rating: Nullable<number>;

}

export interface RevisionModel {
    // Has default value
    revision_id: number;

    // Has default value
    created_at: Date;

    // Has default value
    page_id: number;

    // Has default value
    user_id: number;

    git_commit: string;

    changes: object;

}

export interface RoleMembershipModel {
    // Has default value
    wiki_id: number;

    // Has default value
    role_id: number;

    // Has default value
    user_id: number;

    applied_at: Date;

}

export interface RoleModel {
    // Has default value
    role_id: number;

    // Has default value
    wiki_id: number;

    name: string;

    permset: number;

}

export interface UserModel {
    // Has default value
    user_id: number;

    name: string;

    // Has default value
    created_at: Date;

    email: string;

    // Has default value
    author_page: string;

    // Has default value
    website: string;

    // Has default value
    about: string;

    // Has default value
    location: string;

    // Has default value
    gender: string;

}

export interface WikiMembershipModel {
    // Has default value
    wiki_id: number;

    // Has default value
    user_id: number;

    applied_at: Date;

    joined_at: Date;

}

export interface WikiModel {
    // Has default value
    wiki_id: number;

    slug: string;

    name: string;

    created_at: Date;

}


// vim: set ft=jinja:
