// THIS FILE WAS AUTOGENERATED BY DEEPWELL v0.0.1
// DO NOT EDIT - MODIFY TEMPLATE INSTEAD

type Nullable<T> = T | null;


export interface AuthorModel {
    author_type: string;

    created_at: Date;

    page_id?: number;

    user_id?: number;

}

export interface FileModel {
    description: string;

    file_id?: number;

    file_name: string;

    file_uri: string;

    page_id?: number;

}

export interface PageModel {
    alt_title: Nullable<string>;

    created_at?: Date;

    page_id?: number;

    slug: string;

    tags: string[];

    title: string;

}

export interface ParentModel {
    page_id?: number;

    parented_at: Date;

    parented_by?: number;

    parent_page_id?: number;

}

export interface PasswordModel {
    digest: string;

    hash: Buffer;

    iterations: number;

    key_size: number;

    salt: Buffer;

    user_id?: number;

}

export interface RatingModel {
    page_id?: number;

    rating: number;

    user_id?: number;

}

export interface RatingsHistoryModel {
    created_at?: Date;

    page_id?: number;

    rating: Nullable<number>;

    rating_id?: number;

    user_id?: number;

}

export interface RevisionModel {
    changes: object;

    created_at?: Date;

    git_commit: string;

    page_id?: number;

    revision_id?: number;

    user_id?: number;

}

export interface RoleMembershipModel {
    applied_at: Date;

    role_id?: number;

    user_id?: number;

    wiki_id?: number;

}

export interface RoleModel {
    name: string;

    permset: number;

    role_id?: number;

    wiki_id?: number;

}

export interface UserModel {
    about?: string;

    author_page?: string;

    created_at?: Date;

    email: string;

    gender?: string;

    location?: string;

    name: string;

    user_id?: number;

    website?: string;

}

export interface WikiMembershipModel {
    applied_at: Date;

    joined_at: Date;

    user_id?: number;

    wiki_id?: number;

}

export interface WikiModel {
    created_at: Date;

    name: string;

    slug: string;

    wiki_id?: number;

}


// vim: set ft=jinja:
